### PR TITLE
Minor updates for bundle generation

### PR DESCRIPTION
**Pull request by phantomjinx**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]

**Comment by phantomjinx** [comment]
Added support for mac osx platform differences with sed.

File: script/Makefile [hunk 1]
```diff
@@ -97,6 +100,13 @@ else
 GOBIN=$(shell go env GOBIN)
 endif
 
+# Support sed on mac osx
```
Comment (tadayosi) [inline script/Makefile:103]: We discussed macOS support for the build scripts before and decided that macOS users use gnu-sed instead of the scripts take care of the compatibility. See #3398

Please rever the changes.

**Review by tadayosi — CHANGES_REQUESTED** [review]

File: config/manifests/bases/camel-k.clusterserviceversion.yaml [hunk 2]
```diff
@@ -22,16 +22,16 @@ metadata:
...
     categories: Integration & Delivery
     certified: "false"
-    containerImage: docker.io/apache/camel-k:1.10.0-SNAPSHOT
-    createdAt: 2022-05-31T12:18:30Z
+    containerImage: docker.io/apache/camel-k:X.Y.Z-SNAPSHOT
+    createdAt: 2022-07-05T16:41:32Z
     description: Apache Camel K is a lightweight integration platform, born on Kubernetes,
       with serverless superpowers.
-    operators.operatorframework.io/builder: operator-sdk-v1.3.0
+    operators.operatorframework.io/builder: operator-sdk-v1.16.0
```
Comment (squakez) [inline config/manifests/bases/camel-k.clusterserviceversion.yaml:29]: Do we want to change this? I'd keep it the original version unless there is a reason to change it.

File: config/manifests/bases/camel-k.clusterserviceversion.yaml [hunk 3]
```diff
@@ -150,11 +150,11 @@ spec:
   - email: users@camel.apache.org
     name: The Apache Software Foundation
   maturity: alpha
-  minKubeVersion: 1.11.0
+  minKubeVersion: 1.14.0
```
Comment (squakez) [inline config/manifests/bases/camel-k.clusterserviceversion.yaml:153]: Do we want to change this? I'd keep it the original version unless there is a reason to change it.

File: script/Makefile (hunk 1 above)
Comment (phantomjinx) [reply script/Makefile]: Done

File: config/manifests/bases/camel-k.clusterserviceversion.yaml (hunk 2 above)
Comment (phantomjinx) [reply config/manifests/bases/camel-k.clusterserviceversion.yaml:29]: operator-sdk version in Makefile is 1.16. For what its worth, this is just a notifying property of the version used to build the CSV bundle. It does not actually have any material effect on OLM.

File: config/manifests/bases/camel-k.clusterserviceversion.yaml (hunk 3 above)
Comment (phantomjinx) [reply config/manifests/bases/camel-k.clusterserviceversion.yaml]: Reverted.

**Comment by phantomjinx** [comment]
Tests failing due to e2e compilation error fixed in #3527.

**Review by tadayosi — APPROVED** [review]

**Comment by tadayosi** [comment]
> Tests failing due to e2e compilation error fixed in #3527.

@phantomjinx Let's rebase it after the fix gets merged.

**Comment by phantomjinx** [comment]
Tests a lot more successful now.

**Comment by tadayosi** [comment]
The last failing test is already fixed at main. Let's merge this.
